package main

import "fmt"

// PluginConfig is the configuration for the Codex Subscription plugin.
// It is deserialized from the "config" field in Bifrost's plugin configuration.
type PluginConfig struct {
	// AccessToken is the ChatGPT/Codex session access token (Bearer token from
	// chatgpt.com). If set, this takes precedence over TokenFile.
	// Extract from the Codex CLI's auth storage or a browser session.
	AccessToken string `json:"access_token"`

	// AccountID is the `chatgpt_account_id` claim from the OAuth ID token.
	// It is sent as the `ChatGPT-Account-Id` header to the Codex backend.
	AccountID string `json:"account_id,omitempty"`

	// TokenFile is the path to a JSON file containing OAuth tokens
	// (generated by the codex-sub-login CLI tool).
	// If AccessToken is empty, the plugin reads tokens from this file.
	// Default: ~/.bifrost/codex-auth.json
	TokenFile string `json:"token_file,omitempty"`

	// AuthIssuer is the OAuth issuer URL for token refresh.
	// Only needed if TokenFile is used and token refresh is desired.
	// Default: "https://auth.openai.com"
	AuthIssuer string `json:"auth_issuer,omitempty"`

	// AuthClientID is the OAuth client ID for token refresh.
	// Only needed if TokenFile is used and token refresh is desired.
	// Default: "app_EMoamEEZ73f0CkXaXp7hrann"
	AuthClientID string `json:"auth_client_id,omitempty"`

	// Models is the list of OpenAI model names to intercept.
	// Requests with any of these models (when provider is "openai") will be
	// rerouted through the Codex backend Responses API.
	Models []string `json:"models"`

	// ModelMapping optionally overrides the default OpenAI→Codex model slug mapping.
	ModelMapping map[string]string `json:"model_mapping,omitempty"`

	// APIBase optionally overrides the ChatGPT backend API base URL.
	// Default: "https://chatgpt.com/backend-api"
	APIBase string `json:"api_base,omitempty"`

	// MaxRetries optionally sets the number of retries for failed HTTP calls.
	// Default: 0 (no retries).
	MaxRetries int `json:"max_retries,omitempty"`
}

// DefaultAPIBase is the default ChatGPT backend API base URL.
// The Codex Responses endpoint is appended as /codex/responses.
const DefaultAPIBase = "https://chatgpt.com/backend-api"

// DefaultAuthIssuer is the default OpenAI OAuth issuer URL for token refresh.
// It matches login.DefaultIssuer so the UI redacted view and the runtime agree.
const DefaultAuthIssuer = "https://auth.openai.com"

// DefaultAuthClientID is the default OAuth client ID used by the Codex CLI.
// It matches login.DefaultClientID so the UI redacted view and the runtime agree.
const DefaultAuthClientID = "app_EMoamEEZ73f0CkXaXp7hrann"

// DefaultModelMapping maps OpenAI model names to Codex backend model slugs.
// The Codex backend accepts its own slugs (gpt-5-codex, gpt-5.2-codex, etc.),
// so a request model name that already matches is passed through unchanged.
// Missing keys fall back to the model name itself (identity passthrough).
var DefaultModelMapping = map[string]string{
	// Identity entries: codex slugs the backend already accepts.
	"gpt-5-codex":         "gpt-5-codex",
	"gpt-5.1-codex":       "gpt-5.1-codex",
	"gpt-5.2-codex":       "gpt-5.2-codex",
	"gpt-5.3-codex":       "gpt-5.3-codex",
	"gpt-5.4-codex":       "gpt-5.4-codex",
	"gpt-5.6-sol":         "gpt-5.6-sol",
	"gpt-5-codex-mini":    "gpt-5-codex-mini",
	"gpt-5.2-codex-mini":  "gpt-5.2-codex-mini",
	"gpt-5.3-codex-mini":  "gpt-5.3-codex-mini",
	"gpt-5.4-codex-mini":  "gpt-5.4-codex-mini",
	"gpt-4.1-codex":       "gpt-4.1-codex",
	"gpt-4.1-codex-mini":  "gpt-4.1-codex-mini",
	"gpt-4o-codex":        "gpt-4o-codex",
	"gpt-4o-mini":         "gpt-4o-mini",
	"gpt-4o":              "gpt-4o",

	// Human-facing OpenAI names → Codex backend slugs.
	"gpt-5":               "gpt-5-codex",
	"gpt-5.1":             "gpt-5.1-codex",
	"gpt-5.2":             "gpt-5.2-codex",
	"gpt-5.3":             "gpt-5.3-codex",
	"gpt-5.4":             "gpt-5.4-codex",
	"gpt-5-mini":          "gpt-5-codex-mini",
	"gpt-5-nano":          "gpt-5-nano-codex",
	"o3":                  "o3-codex",
	"o3-mini":             "o3-mini-codex",
	"o4-mini":             "o4-mini-codex",
	"codex":               "gpt-5-codex",
	"codex-mini":          "gpt-5-codex-mini",
}

// ApplyDefaults fills unset fields with their documented defaults. It is safe
// to call on a zero-value or newly-parsed PluginConfig and returns the same
// pointer for chaining.
func (c *PluginConfig) ApplyDefaults() *PluginConfig {
	if c.APIBase == "" {
		c.APIBase = DefaultAPIBase
	}
	if c.AuthIssuer == "" {
		c.AuthIssuer = DefaultAuthIssuer
	}
	if c.AuthClientID == "" {
		c.AuthClientID = DefaultAuthClientID
	}
	return c
}

// Validate checks that the config has a usable token source and that any
// configured model list is non-empty-but-set sensibly. It returns an error for
// configuration that would prevent the plugin from running. A permissive
// empty Models list is allowed (that state means "intercept all mapped models").
func (c *PluginConfig) Validate() error {
	if c == nil {
		return fmt.Errorf("config is nil")
	}
	if c.AccessToken == "" && c.TokenFile == "" {
		return fmt.Errorf("no token source configured: set access_token or token_file")
	}
	return nil
}

// parseConfig converts a generic map to PluginConfig. Field defaults are NOT
// applied here; call ApplyDefaults (via Init or RedactConfig) to fill them.
func parseConfig(cfgMap map[string]any) (*PluginConfig, error) {
	cfg := &PluginConfig{}

	if v, ok := cfgMap["access_token"].(string); ok {
		cfg.AccessToken = v
	}
	if v, ok := cfgMap["account_id"].(string); ok {
		cfg.AccountID = v
	}
	if v, ok := cfgMap["token_file"].(string); ok {
		cfg.TokenFile = v
	}
	if v, ok := cfgMap["auth_issuer"].(string); ok {
		cfg.AuthIssuer = v
	}
	if v, ok := cfgMap["auth_client_id"].(string); ok {
		cfg.AuthClientID = v
	}
	if v, ok := cfgMap["api_base"].(string); ok {
		cfg.APIBase = v
	}
	if v, ok := cfgMap["max_retries"].(float64); ok {
		cfg.MaxRetries = int(v)
	}

	// Parse models list
	if modelsRaw, ok := cfgMap["models"].([]any); ok {
		cfg.Models = make([]string, 0, len(modelsRaw))
		for _, m := range modelsRaw {
			if s, ok := m.(string); ok {
				cfg.Models = append(cfg.Models, s)
			}
		}
	}

	// Parse model mapping
	if mappingRaw, ok := cfgMap["model_mapping"].(map[string]any); ok {
		cfg.ModelMapping = make(map[string]string, len(mappingRaw))
		for k, v := range mappingRaw {
			if s, ok := v.(string); ok {
				cfg.ModelMapping[k] = s
			}
		}
	}

	return cfg, nil
}

// MarshalConfigForStorage converts the live config to DB-storage format.
func MarshalConfigForStorage(config map[string]any) (map[string]any, error) {
	return config, nil
}

// configField describes a single plugin configuration option, used to build the
// canonical (visually renderable) config view and the DescribeConfig export.
type configField struct {
	Key         string // JSON key
	Kind        string // "secret", "path", "string", "bool", "int", "list", "map"
	Description string // short human-readable description for UI tooltips/labels
	Default     any    // effective default when the field is unset (nil if none)
}

// describeConfigFields returns the ordered list of configuration options exposed
// by this plugin. This is the single source of truth for the UI-renderable view;
// it mirrors the PluginConfig struct and its Default* constants.
func describeConfigFields() []configField {
	return []configField{
		{Key: "access_token", Kind: "secret", Description: "ChatGPT/Codex session access token (Bearer). Takes precedence over token_file. If unset, the plugin runs an interactive device flow (URL + one-time code shown in logs/status) to obtain one.", Default: ""},
		{Key: "account_id", Kind: "string", Description: "chatgpt_account_id claim from the OAuth ID token; sent as the ChatGPT-Account-Id header.", Default: ""},
		{Key: "token_file", Kind: "path", Description: "Path to a JSON file containing OAuth tokens. The interactive device flow (auth URL shown in logs/status) writes here on success. Default ~/.bifrost/codex-auth.json.", Default: ""},
		{Key: "auth_issuer", Kind: "string", Description: "OAuth issuer URL used for token refresh.", Default: DefaultAuthIssuer},
		{Key: "auth_client_id", Kind: "string", Description: "OAuth client ID used for token refresh.", Default: DefaultAuthClientID},
		{Key: "api_base", Kind: "string", Description: "Codex backend API base URL.", Default: DefaultAPIBase},
		{Key: "max_retries", Kind: "int", Description: "Number of retries for failed HTTP calls.", Default: 0},
		{Key: "models", Kind: "list", Description: "OpenAI model names to intercept and reroute through the Codex backend.", Default: []string{}},
		{Key: "model_mapping", Kind: "map", Description: "Overrides for the default OpenAI→Codex model slug mapping.", Default: DefaultModelMapping},
	}
}

// RedactConfig builds the API-response (UI-visible) configuration view.
//
// Unlike a naive pass-through, it returns a canonical map containing every
// supported option with its effective value applied (defaults filled in from the
// Default* constants), with secret values masked. This lets the Bifrost UI render
// a complete configuration form even when the user has not set every field.
func RedactConfig(config map[string]any) (map[string]any, error) {
	cfg, err := parseConfig(config)
	if err != nil {
		return nil, err
	}
	cfg.ApplyDefaults()
	return redactedView(cfg), nil
}

// redactedView converts a parsed PluginConfig into the canonical, redacted
// key/value map for API responses. Callers should have applied defaults first.
func redactedView(cfg *PluginConfig) map[string]any {
	if cfg == nil {
		cfg = &PluginConfig{}
	}
	models := cfg.Models
	if models == nil {
		models = []string{}
	}
	mapping := cfg.ModelMapping
	if mapping == nil {
		mapping = map[string]string{}
	}

	return map[string]any{
		"access_token":   redactSecret(cfg.AccessToken),
		"account_id":     cfg.AccountID,
		"token_file":     cfg.TokenFile,
		"auth_issuer":    firstNonEmpty(cfg.AuthIssuer, DefaultAuthIssuer),
		"auth_client_id": firstNonEmpty(cfg.AuthClientID, DefaultAuthClientID),
		"api_base":       firstNonEmpty(cfg.APIBase, DefaultAPIBase),
		"max_retries":    cfg.MaxRetries,
		"models":         models,
		"model_mapping":  mapping,
	}
}

// DescribeConfig returns a human/machine readable description of every
// configuration option this plugin supports. It is an additive export (not part
// of the bifrost loader contract) intended for UIs that want to render a
// configuration form with labels, types, defaults, and descriptions.
func DescribeConfig() map[string]any {
	fields := describeConfigFields()
	out := make(map[string]any, len(fields))
	for _, f := range fields {
		out[f.Key] = map[string]any{
			"kind":        f.Kind,
			"description": f.Description,
			"default":     f.Default,
		}
	}

	// Auth guidance field describing the interactive device flow that the
	// plugin surfaces in logs/status. This makes the plugin description
	// self-documenting about how to authenticate.
	if status := GetAuthStatus(); status != nil {
		out["_auth"] = map[string]any{
			"kind":        "status",
			"description": "Device-flow auth status. When not authenticated the plugin logs the verification URL and one-time code and re-polls until you authorize.",
			"value":       status,
		}
	}
	return out
}

// redactSecret returns "***" for a non-empty secret and "" otherwise, so a UI can
// distinguish "set (hidden)" from "unset".
func redactSecret(v string) string {
	if v == "" {
		return ""
	}
	return "***"
}

// firstNonEmpty returns v when non-empty, otherwise fallback.
func firstNonEmpty(v, fallback string) string {
	if v != "" {
		return v
	}
	return fallback
}